
USE BuyPy;

DROP USER IF EXISTS 'WEB_CLIENT'@'%';
CREATE USER 'WEB_CLIENT'@'%' IDENTIFIED BY 'Lmxy20#a';
GRANT SELECT ON BuyPy.* TO 'WEB_CLIENT'@'%';
GRANT INSERT, UPDATE ON BuyPy.`Client` TO 'WEB_CLIENT'@'%';
GRANT INSERT, UPDATE, DELETE ON BuyPy.Orders TO 'WEB_CLIENT'@'%';
GRANT INSERT, UPDATE, DELETE ON BuyPy.Ordered_Product TO 'WEB_CLIENT'@'%';
GRANT UPDATE (quantity) ON BuyPy.Product TO 'WEB_CLIENT'@'%';
GRANT EXECUTE ON PROCEDURE BuyPy.CreateOrder TO 'WEB_CLIENT'@'%';
GRANT EXECUTE ON PROCEDURE BuyPy.GetOrderTotal TO 'WEB_CLIENT'@'%';
GRANT EXECUTE ON PROCEDURE BuyPy.AddProductToOrder TO 'WEB_CLIENT'@'%';

DROP USER IF EXISTS 'BUYDB_OPERATOR'@'%';
CREATE USER 'BUYDB_OPERATOR'@'%' IDENTIFIED BY 'Lmxy20#a';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE ON BuyPy.* TO 'BUYDB_OPERATOR'@'%';

DROP USER IF EXISTS 'BUYDB_ADMIN'@'%';
CREATE USER 'BUYDB_ADMIN'@'%' IDENTIFIED BY 'Lmxy20#a';
GRANT ALL PRIVILEGES ON BuyPy.* TO 'BUYDB_ADMIN'@'%' WITH GRANT OPTION ;

FLUSH PRIVILEGES;